name: Release Drafter

template: |
  ## What’s Changed

  $CHANGES

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

version-resolver:
  major:
    labels:
      - "SEMVER/major"
  minor:
    labels:
      - "SEMVER/minor"
  patch:
    labels:
      - "SEMVER/patch"
  default: patch
